package com.cell.user.dao.mapper;

import com.cell.user.dao.entiy.SysPermission;
import com.cell.user.dao.entiy.SysPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysPermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int countByExample(SysPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int deleteByExample(SysPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int insert(SysPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int insertSelective(SysPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	List<SysPermission> selectByExample(SysPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	SysPermission selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int updateByExampleSelective(@Param("record") SysPermission record,
			@Param("example") SysPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int updateByExample(@Param("record") SysPermission record,
			@Param("example") SysPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int updateByPrimaryKeySelective(SysPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_permission
	 * @mbggenerated  Fri Mar 24 17:07:32 CST 2017
	 */
	int updateByPrimaryKey(SysPermission record);
}